# baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "pt-br"
title = "Erick Pires"
theme = "casper"

BaseUrl= "http://blog.erickpires.com/"
LanguageCode= "pt-BR"
Title= "Erick Pires"
paginate = 5
DisqusShortname = "erickpires"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  # description = ""
  cover = "images/cover.jpg"
  author = "Erick Pires"
  authorlocation = "Rio de Janeiro, Brazil"
  authorwebsite = "http://erickpires.com"
  bio= "Estudante de Ciência da Computação"
  logo = "images/logo.png"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "erickpires"
  twitterName = "ericktpires"
  facebookName = "ericktpires"
  # linkedinName = ""
  hideHUGOSupport = false

[[menu.main]]
  name = "Erick Pires"
  weight = -120
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Sobre"
  weight = -110
  identifier = "about"
  url = "/about"
